version: "3.6"
networks:
  default:
    external:
      name: yii2_sbmd_app

services:
  sbmd_yii2_platform_nginx:
    image: nginx:latest
    container_name: sbmd_yii2_platform_nginx
    volumes:
      - ./developer/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - sbmd_yii2_platform_php
      - sbmd_yii2_platform_mysql
    ports:
      - 80:80

  sbmd_yii2_platform_php:
    image: php:7.4-fpm
    container_name: sbmd_yii2_platform_php
    build:
      context: ./
      dockerfile: ./developer/Dockerfile
    working_dir: /app
    volumes:
      - ./app/:/app

  sbmd_yii2_platform_mysql:
    image: mysql:5.7
    container_name: sbmd_yii2_platform_mysql
    volumes:
      - ./developer/mysql/dumps:/dumps
    ports:
      - "33067:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main